[package]
name = "lc3-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.182"
windows-sys = { version = "0.61", features = [ "Win32_Foundation", "Win32_System_Console", "Win32_System_Threading",]}
